name: Testing Cloud-Hosted-Guide-Converter

on: [push]

jobs:

    steps:

      # Any prerequisite steps
      - uses: actions/checkout@master
        
      - name: Checkout guide-getting-started
        uses: actions/checkout@v2
        with:
          repository: OpenLiberty/guide-getting-started
          path: guide-getting-started

      - name: Checkout guide-microprofile-reactive-messaging-acknowledgment
        uses: actions/checkout@v2
        with:
          repository: OpenLiberty/guide-microprofile-reactive-messaging-acknowledgment
          path: guide-microprofile-reactive-messaging-acknowledgment
        
      - name: Checkout guides-common repo
        uses: actions/checkout@v2
        with:
          repository: OpenLiberty/guides-common
          path: uides-common

      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Testing with Maven
        run: mvn package
